### ISSUE TITLE
NameError when defining page model

### ISSUE THREAD

**Issue by Plastix** [feincms/feincms#590]
Hey guys,

I'm getting the following error when trying to define a page model. Running Django 1.8 and Python 2.7. Any ideas?

**My Page Model**
```python
from feincms.module.page.models import Page

Page.register_templates({
    'home': _('Home Page'),
    'path': 'myproject/home.html',
    'regions': (
        ('splash', _('Main Splash Name')),
    ),
})
```

**The Stacktrace**
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Plastix/.virtualenvs/myproject/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/Plastix/.virtualenvs/myproject/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/Plastix/.virtualenvs/myproject/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Plastix/.virtualenvs/myproject/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Plastix/.virtualenvs/myproject/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Plastix/MyProject/myproject/models.py", line 50, in <module>
    'home': _('Home Page'),
NameError: name '_' is not defined
```

**Comment by Plastix** [comment]
Oh my bad I didn't read the docs correctly!
