### ISSUE TITLE
Hello world for FeinCMS?

### ISSUE THREAD

**Issue by troelsfr** [feincms/feincms#649]
Hey,

FeinCMS seems to be exactly what I am looking for for one of my projects. However, I think the documentation is outdated? If I following the installation and configuration guide on readthedocs, I cannot get FeinCMS to work. Do you have a minimal example project somewhere that I could have a look at?

Here is what I've done:

```
tfr@Desktop-tfr:~/Downloads$ sudo pip install feincms
[sudo] password for tfr: 
Collecting feincms
  Downloading FeinCMS-1.13.1-py2.py3-none-any.whl (450kB)
    100% |████████████████████████████████| 450kB 670kB/s 
Installing collected packages: feincms
Successfully installed feincms-1.13.1
tfr@Desktop-tfr:~/Downloads$ django-admin --version
1.10.6
tfr@Desktop-tfr:~/Downloads$ django-admin startproject feintest
tfr@Desktop-tfr:~/Downloads$ cd feintest/
tfr@Desktop-tfr:~/Downloads/feintest$ emacs feintest/settings.py 
tfr@Desktop-tfr:~/Downloads/feintest$ ./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named mptt
tfr@Desktop-tfr:~/Downloads/feintest$ sudo pip install django-mptt
Collecting django-mptt
  Downloading django_mptt-0.8.7-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 644kB/s 
Installing collected packages: django-mptt
Successfully installed django-mptt-0.8.7
tfr@Desktop-tfr:~/Downloads/feintest$ ./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/feincms/module/page/admin.py", line 23, in <module>
    "The page module requires a 'Page.register_templates()' call "
django.core.exceptions.ImproperlyConfigured: The page module requires a 'Page.register_templates()' call somewhere ('Page.register_regions()' is not sufficient). If you're not using the default Page admin, maybe try FEINCMS_USE_PAGE_ADMIN=False to avoid this warning.
tfr@Desktop-tfr:~/Downloads/feintest$ ./manage.py startapp testpage
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/feincms/module/page/admin.py", line 23, in <module>
    "The page module requires a 'Page.register_templates()' call "
django.core.exceptions.ImproperlyConfigured: The page module requires a 'Page.register_templates()' call somewhere ('Page.register_regions()' is not sufficient). If you're not using the default Page admin, maybe try FEINCMS_USE_PAGE_ADMIN=False to avoid this warning.
tfr@Desktop-tfr:~/Downloads/feintest$ emacs feintest/settings.py
tfr@Desktop-tfr:~/Downloads/feintest$ ./manage.py startapp testpage
tfr@Desktop-tfr:~/Downloads/feintest$ emacs testpage/models.py feintest/settings.py
tfr@Desktop-tfr:~/Downloads/feintest$ ./manage.py makemigrations
No changes detected
tfr@Desktop-tfr:~/Downloads/feintest$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK
tfr@Desktop-tfr:~/Downloads/feintest$ ./manage.py runserver
```

As you can see there are no tables created for Page nor for the testpage app. Any suggestion to what I might be doing wrong would be very welcome. I've tried on a couple of different computers with different versions of Django, but with no luck.

**Comment by mvcoding** [comment]
Hey,

check out issue #625 for more details. The problem is that Django 1.9+ doesn't create tables for apps without migrations and FeinCMS has none by default.

It should be enough to run migrate with the --run-syncdb argument to create the tables:
https://docs.djangoproject.com/en/1.10/ref/django-admin/#cmdoption-migrate-run-syncdb

If that doesn't work, you can explicitly add migrations for the page app:
https://feincms-django-cms.readthedocs.io/en/latest/migrations.html

**Comment by matthiask** [comment]
You can and you should use migrations with or without FeinCMS. Sooner or later you'll want to change the schema, add content types or something and this will be much easier with migrations.

It's unfortunate though that `startapp` does not work anymore without proper configuration (e.g. `register_templates` and friends).

**Comment by jwadden** [comment]
The instructions that @mvcoding linked to regarding adding migrations for the page app don't work. I've created issue #652 explaining the problem.

**Comment by troelsfr** [comment]
Cheers guys. I'll see if I can make things work based on this :)

**Comment by matthiask** [comment]
I'm going to close this and point everyone towards https://feincms3.readthedocs.io/en/latest/build-your-cms.html
