### ISSUE TITLE
FeinCMS prevents migration in Django 1.11

### ISSUE THREAD

**Issue by chrisspen** [feincms/feincms#655]
I'm trying to upgrade my project to Django 1.11, and when I try to run `manage.py makemigrations myapp`, I get the error:

    Traceback (most recent call last):
      File "manage.py", line 9, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
        utility.execute()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
        django.setup()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
        app_config.import_models()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
        self.models_module = import_module(models_module_name)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/feincms/models.py", line 16, in <module>
        from django.contrib.contenttypes.models import ContentType
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 139, in <module>
        class ContentType(models.Model):
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/models/base.py", line 118, in __new__
        "INSTALLED_APPS." % (module, name)
    RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

This error is common in Django apps that haven't been upgraded to Django 1.10+. However, from the Travis tests, it looks like you officially support Django 1.11. Why is FeinCMS triggering and exception from ContentTypes?

**Comment by matthiask** [comment]
Hmm. Did you remove `django.contrib.contenttypes` from `INSTALLED_APPS` by chance? FeinCMS seems to depend on the contenttypes app, probably because we are using the contenttypes' ID for a cache key somewhere.

**Comment by chrisspen** [comment]
No, I haven't changed anything in my `INSTALLED_APPS`. It seems to be a bug in Django 1.11. I was trying to make migrations for just a single app, and apparently that's no longer fully supported. When I removed the app name, it ran without error.
