### ISSUE TITLE
Unable to run migrations in Django 1.11

### ISSUE THREAD

**Issue by chrisspen** [feincms/feincms#658]
I recently tried deleting, regenerating, and re-running all my migrations on a fresh database, and I'm finding that `manage.py migrate` fails with:

    Applying page.0001_initial...Traceback (most recent call last):
      File "manage.py", line 9, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
        utility.execute()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
        output = self.handle(*args, **options)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
        fake_initial=fake_initial,
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
        state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
        state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
        state = migration.apply(state, schema_editor)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 93, in __exit__
        self.execute(sql)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 120, in execute
        cursor.execute(sql, params)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.ProgrammingError: relation "medialibrary_mediafile" does not exist

The command `manage.py makemigrations` ran without error, so I'm a little perplexed why completely auto-generated migrations would be broken.

I do have a custom Page model, but I believe I'm following all the steps as explained in the [docs](https://feincms-django-cms.readthedocs.io/en/latest/page.html). Unfortunately, the error message doesn't really help me. Clearly, it seems to be running the migrations for my custom app before FeinCMS's own migrations, but as the migrations were auto-generated, I'm not sure how I can fix this.

How would I go about diagnosing this? Is this a bug in FeinCMS, Django or my own code?

**Comment by chrisspen** [comment]
Oddly, my custom page migration does contain the dependency:

     ('medialibrary', '__first__'),

so I'm not sure why it's not running `medialibrary` migrations first.

If I first try running:

     manage.py migrate medialibrary

I get the error:

    CommandError: App 'medialibrary' does not have migrations.

Looking through the code, sure enough, there are no migrations in `feincms/module/medialibrary`. Is this intentional? Do I need to manage those myself?

**Comment by matthiask** [comment]
Unfortunately yes; you'll have to `manage.py makemigrations medialibrary` as well, and also add the corresponding `MIGRATION_MODULES` entry.

The reason for this is that `MediaFile` also extends `ExtensionsMixin`, which means that the media library models might not look the same in all installations of FeinCMS.

**Comment by chrisspen** [comment]
Ah, ok. Yeah, after I added `medialibrary` to `settings.MIGRATION_MODULES` and re-ran `makemigrations`, everything worked. Strange I never ran into this before. Thanks for your help.
